// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MySecondBrain.Data;

#nullable disable

namespace MySecondBrain.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.28");

            modelBuilder.Entity("MySecondBrain.Data.Entities.ApiKey", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomEndpointUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomProviderName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsValid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastTestedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("MySecondBrain.Data.Entities.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("MySecondBrain.Data.Entities.Artifact", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThreadId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ThreadId");

                    b.ToTable("Artifacts");
                });

            modelBuilder.Entity("MySecondBrain.Data.Entities.ChatThread", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChatMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorLabel")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMuted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTransient")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastActivityAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelConfigId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalHighlightedText")
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceAppName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceDocTitle")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SourceHWND")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SystemMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ThinkingEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("IsTransient");

                    b.HasIndex("LastActivityAt");

                    b.HasIndex("ModelConfigId");

                    b.HasIndex("PersonaId");

                    b.ToTable("ChatThreads");
                });

            modelBuilder.Entity("MySecondBrain.Data.Entities.MediaItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GeneratedPrompt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSavedToDisk")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSavedToWiki")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThreadId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.HasIndex("ThreadId");

                    b.ToTable("MediaItems");
                });

            modelBuilder.Entity("MySecondBrain.Data.Entities.Message", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BranchId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EstimatedCost")
                        .HasColumnType("TEXT");

                    b.Property<string>("Feedback")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<long?>("GenerationTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActiveBranch")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsDirectTransformation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelConfigId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentMessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawContent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThreadId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenCount")
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ModelConfigId");

                    b.HasIndex("ParentMessageId");

                    b.HasIndex("PersonaId");

                    b.HasIndex("ThreadId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("MySecondBrain.Data.Entities.MessageDrafts", b =>
                {
                    b.Property<string>("ThreadId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CursorPosition")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("SavedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ThreadId");

                    b.ToTable("MessageDrafts");
                });

            modelBuilder.Entity("MySecondBrain.Data.Entities.ModelConfiguration", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKeyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContextOverflowStrategy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxContextWindow")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxOutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelIdentifier")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PricingInputPer1K")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PricingOutputPer1K")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("Temperature")
                        .HasColumnType("REAL");

                    b.Property<bool>("ThinkingEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApiKeyId");

                    b.HasIndex("DisplayName")
                        .IsUnique();

                    b.ToTable("ModelConfigurations");
                });

            modelBuilder.Entity("MySecondBrain.Data.Entities.Persona", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultChatMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultModelConfigId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SystemPrompt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DefaultModelConfigId");

                    b.HasIndex("DisplayName")
                        .IsUnique();

                    b.ToTable("Personas");

                    b.HasData(
                        new
                        {
                            Id = "00000000000000000000000000000001",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DefaultChatMode = "Standard",
                            DisplayName = "General Assistant",
                            IsBuiltIn = true,
                            SystemPrompt = "You are a helpful, thoughtful assistant.",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "00000000000000000000000000000002",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DefaultChatMode = "Standard",
                            DisplayName = "Code Helper",
                            IsBuiltIn = true,
                            SystemPrompt = "You are an expert software developer. Provide clean, well-documented code.",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("MySecondBrain.Data.Entities.PromptTemplate", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PromptTemplates");
                });

            modelBuilder.Entity("MySecondBrain.Data.Entities.TextAction", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApplyMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CaptureScope")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Hotkey")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelConfigId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModelConfigId");

                    b.ToTable("TextActions");

                    b.HasData(
                        new
                        {
                            Id = "a000000000000000000000000000001",
                            ApplyMode = "replaceSelection",
                            CaptureScope = "selection",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Rewrite",
                            Hotkey = "Alt+Q",
                            IsBuiltIn = true,
                            SystemPrompt = "Rewrite the following text to improve clarity, flow, and impact while preserving the original meaning.",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "a000000000000000000000000000002",
                            ApplyMode = "showOnly",
                            CaptureScope = "selection",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Summarize",
                            Hotkey = "Alt+W",
                            IsBuiltIn = true,
                            SystemPrompt = "Summarize the following text concisely, capturing the key points.",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "a000000000000000000000000000003",
                            ApplyMode = "showOnly",
                            CaptureScope = "selection",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Explain",
                            Hotkey = "Alt+E",
                            IsBuiltIn = true,
                            SystemPrompt = "Explain the following text clearly and thoroughly, as if teaching someone new to the topic.",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "a000000000000000000000000000004",
                            ApplyMode = "replaceSelection",
                            CaptureScope = "selection",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Translate",
                            Hotkey = "Alt+R",
                            IsBuiltIn = true,
                            SystemPrompt = "Translate the following text to English. Preserve formatting and tone.",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "a000000000000000000000000000005",
                            ApplyMode = "replaceSelection",
                            CaptureScope = "selection",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Fix Grammar",
                            IsBuiltIn = true,
                            SystemPrompt = "Fix grammar, spelling, and punctuation errors in the following text. Preserve the original meaning and style.",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "a000000000000000000000000000006",
                            ApplyMode = "replaceSelection",
                            CaptureScope = "selection",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Enhance Prompt",
                            IsBuiltIn = true,
                            SystemPrompt = "Improve the following prompt to be more specific, detailed, and effective. Add relevant context and constraints.",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "a000000000000000000000000000007",
                            ApplyMode = "insertAtCursor",
                            CaptureScope = "focusedElement",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Continue Writing",
                            Hotkey = "Alt+C",
                            IsBuiltIn = true,
                            SystemPrompt = "Continue writing from where the text left off. Match the existing tone, style, and formatting. Maintain coherence with the preceding content.",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "a000000000000000000000000000008",
                            ApplyMode = "replaceFocusedElement",
                            CaptureScope = "focusedElement",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Improve Flow",
                            IsBuiltIn = true,
                            SystemPrompt = "Rewrite the following text to improve logical flow, transitions between ideas, and overall readability while preserving the original meaning.",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "a000000000000000000000000000009",
                            ApplyMode = "showOnly",
                            CaptureScope = "fullDocument",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Summarize Page",
                            IsBuiltIn = true,
                            SystemPrompt = "Summarize the following content concisely, capturing the key points and overall structure.",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "a000000000000000000000000000010",
                            ApplyMode = "showOnly",
                            CaptureScope = "fullDocument,screenshot",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Explain Screen",
                            IsBuiltIn = true,
                            SystemPrompt = "Explain what is shown in the provided content. Describe the layout, key elements, and purpose clearly.",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("MySecondBrain.Data.Entities.UsageRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("CompletionTokens")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EstimatedCost")
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelConfigId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelIdentifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonaId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PromptTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThreadId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalTokens")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.HasIndex("ModelConfigId");

                    b.HasIndex("PersonaId");

                    b.HasIndex("ThreadId");

                    b.ToTable("UsageRecords");
                });

            modelBuilder.Entity("MySecondBrain.Data.Entities.WikiFile", b =>
                {
                    b.Property<string>("FilePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<string>("CrossLinksIn")
                        .HasColumnType("TEXT");

                    b.Property<string>("CrossLinksOut")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("H1Title")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Headings")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("WordCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("FilePath");

                    b.ToTable("WikiFiles");
                });

            modelBuilder.Entity("MySecondBrain.Data.Entities.WikiVersionSnapshot", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("WikiFilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WikiFilePath");

                    b.ToTable("WikiVersionSnapshots");
                });

            modelBuilder.Entity("MySecondBrain.Data.Entities.Artifact", b =>
                {
                    b.HasOne("MySecondBrain.Data.Entities.ChatThread", "Thread")
                        .WithMany("Artifacts")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("MySecondBrain.Data.Entities.ChatThread", b =>
                {
                    b.HasOne("MySecondBrain.Data.Entities.ModelConfiguration", "ModelConfig")
                        .WithMany("ChatThreads")
                        .HasForeignKey("ModelConfigId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MySecondBrain.Data.Entities.Persona", "Persona")
                        .WithMany("ChatThreads")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ModelConfig");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("MySecondBrain.Data.Entities.MediaItem", b =>
                {
                    b.HasOne("MySecondBrain.Data.Entities.Message", "Message")
                        .WithMany("MediaItems")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MySecondBrain.Data.Entities.ChatThread", "Thread")
                        .WithMany("MediaItems")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("MySecondBrain.Data.Entities.Message", b =>
                {
                    b.HasOne("MySecondBrain.Data.Entities.ModelConfiguration", "ModelConfig")
                        .WithMany("Messages")
                        .HasForeignKey("ModelConfigId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MySecondBrain.Data.Entities.Message", "ParentMessage")
                        .WithMany("ChildMessages")
                        .HasForeignKey("ParentMessageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MySecondBrain.Data.Entities.Persona", "Persona")
                        .WithMany("Messages")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MySecondBrain.Data.Entities.ChatThread", "Thread")
                        .WithMany("Messages")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModelConfig");

                    b.Navigation("ParentMessage");

                    b.Navigation("Persona");

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("MySecondBrain.Data.Entities.ModelConfiguration", b =>
                {
                    b.HasOne("MySecondBrain.Data.Entities.ApiKey", "ApiKey")
                        .WithMany("ModelConfigurations")
                        .HasForeignKey("ApiKeyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ApiKey");
                });

            modelBuilder.Entity("MySecondBrain.Data.Entities.Persona", b =>
                {
                    b.HasOne("MySecondBrain.Data.Entities.ModelConfiguration", "DefaultModelConfig")
                        .WithMany("Personas")
                        .HasForeignKey("DefaultModelConfigId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DefaultModelConfig");
                });

            modelBuilder.Entity("MySecondBrain.Data.Entities.TextAction", b =>
                {
                    b.HasOne("MySecondBrain.Data.Entities.ModelConfiguration", "ModelConfig")
                        .WithMany("TextActions")
                        .HasForeignKey("ModelConfigId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ModelConfig");
                });

            modelBuilder.Entity("MySecondBrain.Data.Entities.UsageRecord", b =>
                {
                    b.HasOne("MySecondBrain.Data.Entities.Message", "Message")
                        .WithOne("UsageRecord")
                        .HasForeignKey("MySecondBrain.Data.Entities.UsageRecord", "MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MySecondBrain.Data.Entities.ModelConfiguration", "ModelConfig")
                        .WithMany("UsageRecords")
                        .HasForeignKey("ModelConfigId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MySecondBrain.Data.Entities.Persona", "Persona")
                        .WithMany("UsageRecords")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MySecondBrain.Data.Entities.ChatThread", "Thread")
                        .WithMany("UsageRecords")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");

                    b.Navigation("ModelConfig");

                    b.Navigation("Persona");

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("MySecondBrain.Data.Entities.WikiVersionSnapshot", b =>
                {
                    b.HasOne("MySecondBrain.Data.Entities.WikiFile", "WikiFile")
                        .WithMany("WikiVersionSnapshots")
                        .HasForeignKey("WikiFilePath")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WikiFile");
                });

            modelBuilder.Entity("MySecondBrain.Data.Entities.ApiKey", b =>
                {
                    b.Navigation("ModelConfigurations");
                });

            modelBuilder.Entity("MySecondBrain.Data.Entities.ChatThread", b =>
                {
                    b.Navigation("Artifacts");

                    b.Navigation("MediaItems");

                    b.Navigation("Messages");

                    b.Navigation("UsageRecords");
                });

            modelBuilder.Entity("MySecondBrain.Data.Entities.Message", b =>
                {
                    b.Navigation("ChildMessages");

                    b.Navigation("MediaItems");

                    b.Navigation("UsageRecord");
                });

            modelBuilder.Entity("MySecondBrain.Data.Entities.ModelConfiguration", b =>
                {
                    b.Navigation("ChatThreads");

                    b.Navigation("Messages");

                    b.Navigation("Personas");

                    b.Navigation("TextActions");

                    b.Navigation("UsageRecords");
                });

            modelBuilder.Entity("MySecondBrain.Data.Entities.Persona", b =>
                {
                    b.Navigation("ChatThreads");

                    b.Navigation("Messages");

                    b.Navigation("UsageRecords");
                });

            modelBuilder.Entity("MySecondBrain.Data.Entities.WikiFile", b =>
                {
                    b.Navigation("WikiVersionSnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
